// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getCell1d
NumericVector getCell1d(int xcell, double xmin, double xmax, NumericVector x);
RcppExport SEXP _rgrids_getCell1d(SEXP xcellSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type xcell(xcellSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(getCell1d(xcell, xmin, xmax, x));
    return rcpp_result_gen;
END_RCPP
}
// getCell2d
NumericVector getCell2d(int xcell, int ycell, double xmin, double xmax, double ymin, double ymax, NumericVector x, NumericVector y);
RcppExport SEXP _rgrids_getCell2d(SEXP xcellSEXP, SEXP ycellSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type xcell(xcellSEXP);
    Rcpp::traits::input_parameter< int >::type ycell(ycellSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(getCell2d(xcell, ycell, xmin, xmax, ymin, ymax, x, y));
    return rcpp_result_gen;
END_RCPP
}
// getCell3d
NumericVector getCell3d(int xcell, int ycell, int zcell, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax, NumericVector x, NumericVector y, NumericVector z);
RcppExport SEXP _rgrids_getCell3d(SEXP xcellSEXP, SEXP ycellSEXP, SEXP zcellSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP, SEXP zminSEXP, SEXP zmaxSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type xcell(xcellSEXP);
    Rcpp::traits::input_parameter< int >::type ycell(ycellSEXP);
    Rcpp::traits::input_parameter< int >::type zcell(zcellSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type zmin(zminSEXP);
    Rcpp::traits::input_parameter< double >::type zmax(zmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(getCell3d(xcell, ycell, zcell, xmin, xmax, ymin, ymax, zmin, zmax, x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// getCoords1d
NumericVector getCoords1d(unsigned xcell, double xmin, double xmax, NumericVector cell);
RcppExport SEXP _rgrids_getCoords1d(SEXP xcellSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned >::type xcell(xcellSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell(cellSEXP);
    rcpp_result_gen = Rcpp::wrap(getCoords1d(xcell, xmin, xmax, cell));
    return rcpp_result_gen;
END_RCPP
}
// getCoords2d
NumericMatrix getCoords2d(unsigned xcell, unsigned ycell, double xmin, double xmax, double ymin, double ymax, NumericVector cell);
RcppExport SEXP _rgrids_getCoords2d(SEXP xcellSEXP, SEXP ycellSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP, SEXP cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned >::type xcell(xcellSEXP);
    Rcpp::traits::input_parameter< unsigned >::type ycell(ycellSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell(cellSEXP);
    rcpp_result_gen = Rcpp::wrap(getCoords2d(xcell, ycell, xmin, xmax, ymin, ymax, cell));
    return rcpp_result_gen;
END_RCPP
}
// getCoords3d
NumericMatrix getCoords3d(int xcell, int ycell, int zcell, double xmin, double xmax, double ymin, double ymax, double zmin, double zmax, NumericVector cell);
RcppExport SEXP _rgrids_getCoords3d(SEXP xcellSEXP, SEXP ycellSEXP, SEXP zcellSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP, SEXP zminSEXP, SEXP zmaxSEXP, SEXP cellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type xcell(xcellSEXP);
    Rcpp::traits::input_parameter< int >::type ycell(ycellSEXP);
    Rcpp::traits::input_parameter< int >::type zcell(zcellSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type zmin(zminSEXP);
    Rcpp::traits::input_parameter< double >::type zmax(zmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell(cellSEXP);
    rcpp_result_gen = Rcpp::wrap(getCoords3d(xcell, ycell, zcell, xmin, xmax, ymin, ymax, zmin, zmax, cell));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rgrids_getCell1d", (DL_FUNC) &_rgrids_getCell1d, 4},
    {"_rgrids_getCell2d", (DL_FUNC) &_rgrids_getCell2d, 8},
    {"_rgrids_getCell3d", (DL_FUNC) &_rgrids_getCell3d, 12},
    {"_rgrids_getCoords1d", (DL_FUNC) &_rgrids_getCoords1d, 4},
    {"_rgrids_getCoords2d", (DL_FUNC) &_rgrids_getCoords2d, 7},
    {"_rgrids_getCoords3d", (DL_FUNC) &_rgrids_getCoords3d, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_rgrids(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
