# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.getCell1d <- function(xcell, xmin, xmax, x) {
    .Call('_rgrids_getCell1d', PACKAGE = 'rgrids', xcell, xmin, xmax, x)
}

.getCell2d <- function(xcell, ycell, xmin, xmax, ymin, ymax, x, y) {
    .Call('_rgrids_getCell2d', PACKAGE = 'rgrids', xcell, ycell, xmin, xmax, ymin, ymax, x, y)
}

.getCell3d <- function(xcell, ycell, zcell, xmin, xmax, ymin, ymax, zmin, zmax, x, y, z) {
    .Call('_rgrids_getCell3d', PACKAGE = 'rgrids', xcell, ycell, zcell, xmin, xmax, ymin, ymax, zmin, zmax, x, y, z)
}

.getCount1d <- function(xcell, xmin, xmax, cell) {
    .Call('_rgrids_getCount1d', PACKAGE = 'rgrids', xcell, xmin, xmax, cell)
}

.getCount2d <- function(xcell, ycell, xmin, xmax, ymin, ymax, cell) {
    .Call('_rgrids_getCount2d', PACKAGE = 'rgrids', xcell, ycell, xmin, xmax, ymin, ymax, cell)
}

.getCount3d <- function(xcell, ycell, zcell, xmin, xmax, ymin, ymax, zmin, zmax, cell) {
    .Call('_rgrids_getCount3d', PACKAGE = 'rgrids', xcell, ycell, zcell, xmin, xmax, ymin, ymax, zmin, zmax, cell)
}

